import 'package:flutter/material.dart';

const Color kBackgroundColor = Color(0xFF111111);
const Color kPrimaryColor = Color(0xFFF6E6A5);
const Color kSecondaryColor = Color(0XFF3971B8);
const kSecondaryOlive = Color(0xFF343B1B);
const Color kSoftYellow = Color(0xFFFBFCEC);
const Color kGreenAccentColor = Color(0XFFCDDC39);
const Color kOrangeAccentColor = Color(0XFFFAA82C);
const Color kBlueAccentColor = Color(0XFF0CAEDD);
const Color kBlueColor = Color(0XFF5C99EE);
const Color kYellowAccentColor = Color(0XFFCDDC39);
const Color kRedAccentColor = Color(0xFFF15A25);
const Color kDarkGreyColor = Color(0XFF333333);
const Color kGreyColor = Color(0XFF808080);
const Color kWhiteColor = Color(0XFFFFFFFF);
const Color kLightGreyColor = Color(0XFFCFCFCF);
const Color kEmeraldGreenColor= Color(0XFF1Cb08F);
final kBlue = const Color(0xFF4F8BFF);
final kGreen = const Color(0xFF2DBE7B);
final kRed = const Color(0xFFE05555);
final kGrey = Colors.grey.shade600;
final kDeepBlueGrayColor= const Color(0xFF344761);
