name: hr_app
description: "MOC HR-App project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #routing
  go_router: ^16.0.0

  #riverpod:
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #localization:
  easy_localization: ^3.0.7+1

  #network:
  dio: ^5.8.0+1

  #cached_network_image:
  cached_network_image: ^3.4.1

  #get_storage:
  get_storage: ^2.1.1

  #intl:
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  custom_lint:
  riverpod_lint:
  riverpod_generator:

flutter:
  uses-material-design: true

  #---------------- ./ LOCAL ASSETS ----------------#
  assets:
    - assets/images/
    - assets/svgs/

  #---------------- ./ LOCAL FONTS ----------------#
#  fonts:
#    - family: Jaldi
#      fonts:
#        - asset: fonts/jaldi_regular.ttf