// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACKDAGlktHqwPM15D10wISyf5RQZJAbkg',
    appId: '1:792976705828:web:28a5de840a319cb2d98bb1',
    messagingSenderId: '792976705828',
    projectId: 'hr-app-75c8d',
    authDomain: 'hr-app-75c8d.firebaseapp.com',
    storageBucket: 'hr-app-75c8d.firebasestorage.app',
    measurementId: 'G-2JQHW94V7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8ySTmPzogrQCK9hnwSB_ObUyaDbbmgU',
    appId: '1:792976705828:android:f5f70fea49fd3b6cd98bb1',
    messagingSenderId: '792976705828',
    projectId: 'hr-app-75c8d',
    storageBucket: 'hr-app-75c8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rpB9JS0pnqrvTKsKWy10f6N8Vi-M7pE',
    appId: '1:792976705828:ios:e8999e06253e265ad98bb1',
    messagingSenderId: '792976705828',
    projectId: 'hr-app-75c8d',
    storageBucket: 'hr-app-75c8d.firebasestorage.app',
    iosBundleId: 'com.example.hrApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5rpB9JS0pnqrvTKsKWy10f6N8Vi-M7pE',
    appId: '1:792976705828:ios:285ab620c6153098d98bb1',
    messagingSenderId: '792976705828',
    projectId: 'hr-app-75c8d',
    storageBucket: 'hr-app-75c8d.firebasestorage.app',
    iosBundleId: 'com.example.hrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACKDAGlktHqwPM15D10wISyf5RQZJAbkg',
    appId: '1:792976705828:web:99434b5aa00f3592d98bb1',
    messagingSenderId: '792976705828',
    projectId: 'hr-app-75c8d',
    authDomain: 'hr-app-75c8d.firebaseapp.com',
    storageBucket: 'hr-app-75c8d.firebasestorage.app',
    measurementId: 'G-K9267CN8RP',
  );
}
